# Generated by Django 2.2.7 on 2020-03-12 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menutype'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('conOFtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='con_of_type', to='menu.MenuType')),
            ],
        ),
    ]
