# Generated by Django 2.2.7 on 2020-06-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_menucontent_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapURL', models.URLField(max_length=300)),
            ],
        ),
    ]
