# Generated by Django 2.2.7 on 2020-06-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_mapbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapbox',
            name='mapURL',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
