# Generated by Django 2.2.7 on 2020-08-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_mapbox_mapactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type1', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
