# Generated by Django 2.2.7 on 2020-08-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_sessiontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberOFseats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_seats1', models.IntegerField(blank=True)),
            ],
        ),
    ]
