# Generated by Django 2.2.7 on 2020-08-03 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_auto_20200803_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberofseats',
            name='number_of_seats1',
            field=models.CharField(blank=True, help_text='مثل: 10 مقاعد', max_length=10, verbose_name='عدد المقاعد'),
        ),
        migrations.CreateModel(
            name='ForReser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_seats', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.NumberOFseats', verbose_name='عدد المقاعد')),
                ('session_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.SessionType', verbose_name='نوع الجلسة')),
            ],
        ),
    ]
