# Generated by Django 2.2.7 on 2020-08-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_auto_20200803_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='forreser',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
