# Generated by Django 2.2.7 on 2020-08-06 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_forreser_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forreser',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='forreser',
            name='session_date',
            field=models.DateTimeField(blank=True, help_text='YY-MM-DD hh:mm:ss', null=True, verbose_name='التوقيت'),
        ),
    ]
