# Generated by Django 2.2.7 on 2021-01-01 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_auto_20200806_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='forreser',
            name='session_time',
            field=models.TimeField(null=True, verbose_name='التوقيت'),
        ),
        migrations.AlterField(
            model_name='forreser',
            name='mobile_number',
            field=models.CharField(help_text='مثال:0511111111', max_length=10, null=True, verbose_name='رقم الجوال'),
        ),
        migrations.AlterField(
            model_name='forreser',
            name='number_of_seats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.NumberOFseats', verbose_name='عدد المقاعد'),
        ),
        migrations.AlterField(
            model_name='forreser',
            name='session_date',
            field=models.DateField(null=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='forreser',
            name='session_duration',
            field=models.FloatField(help_text='ساعة', null=True, verbose_name='مدة الجلسة'),
        ),
        migrations.AlterField(
            model_name='forreser',
            name='session_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.SessionType', verbose_name='نوع الجلسة'),
        ),
    ]
